using MaternityCareSystem.Areas.PN.DataModels;
using MaternityCareSystem.Domain;
using MaternityCareSystem.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;

namespace MaternityCareSystem.Areas.PN.BL
{
    public class InfantBL:VirtualCrud<PostNatal_Infant>
    {
        public override PostNatal_Infant Save(PostNatal_Infant model, out OutParamModel outparam)
        {
            outparam = new OutParamModel();
            SqlParameter _error = new SqlParameter()
            {
                ParameterName = "@Error",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Bit

            };
            SqlParameter _message = new SqlParameter()
            {
                ParameterName = "@Message",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.NVarChar,
                Size = 200
            };
            SqlParameter _ID = new SqlParameter()
            {
                ParameterName = "@ID",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
                Value = 0
            };
            SqlParameter[] parameters =
            {
                  new SqlParameter("@PatientId",model.PatientId ?? (object)DBNull.Value)
                 ,new SqlParameter("@InfantDOB",model.InfantDOB ?? (object)DBNull.Value)
                 ,new SqlParameter("@InfantAge",model.InfantAge ?? (object)DBNull.Value)
                 ,new SqlParameter("@Gender",model.Gender ?? (object)DBNull.Value)
                 ,new SqlParameter("@DeliveryCondition",model.DeliveryCondition ?? (object)DBNull.Value)
                 ,new SqlParameter("@DeliveryTerm",model.DeliveryTerm ?? (object)DBNull.Value)
                 ,new SqlParameter("@DeliveryHospital",model.DeliveryHospital )
                 ,new SqlParameter("@DeliveryMaternityHome",model.DeliveryMaternityHome )
                 ,new SqlParameter("@DeliveryHome",model.DeliveryHome)
                 ,new SqlParameter("@Alert", model.Alert)
                 ,new SqlParameter("@ListLess", model.Listless)
                 ,new SqlParameter("@Jaundice", model.Jaundice)
                 ,new SqlParameter("@Active", model.Active)
                 ,new SqlParameter("@Agitated", model.Agitated)
                 ,new SqlParameter("@Pale", model.Pale)
                 ,new SqlParameter("@Smiling", model.Smiling)
                 ,new SqlParameter("@Convulsions", model.Convulsions)
                 ,new SqlParameter("@Crying", model.Crying)
                 ,new SqlParameter("@NonResponse", model.NonResponse)
                 ,new SqlParameter("@Lethargic", model.Lethargic)
                 ,new SqlParameter("@ColorPink", model.ColorPink)
                 ,new SqlParameter("@Other", model.Other)
                 ,new SqlParameter("@InfantCondition",model.InfantCondition ?? (object)DBNull.Value)
                 ,new SqlParameter("@BreastFeeding", model.BreastFeeding)
                 ,new SqlParameter("@FeedingCondition",model.FeedingCondition ?? (object)DBNull.Value)
                 ,new SqlParameter("@Temperature",model.Temperature ?? (object)DBNull.Value)
                 ,new SqlParameter("@Weight",model.Weight ?? (object)DBNull.Value)
                 ,new SqlParameter("@WeightPercentile",model.WeightPercentile ?? (object)DBNull.Value)
                 ,new SqlParameter("@BirthWieght",model.BirthWieght ?? (object)DBNull.Value)
                 ,new SqlParameter("@BirthWieghtPercentile",model.BirthWieghtPercentile ?? (object)DBNull.Value)
                 ,new SqlParameter("@Length",model.Length ?? (object)DBNull.Value)
                 ,new SqlParameter("@LengthPercentile",model.LengthPercentile ?? (object)DBNull.Value)
                 ,new SqlParameter("@HC",model.HC ?? (object)DBNull.Value)
                 ,new SqlParameter("@HCPercentile",model.HCPercentile ?? (object)DBNull.Value)
                 ,new SqlParameter("@Head",model.Head ?? (object)DBNull.Value)
                 ,new SqlParameter("@AntFontAnelle",model.AntFontAnelle ?? (object)DBNull.Value)
                 ,new SqlParameter("@PostFontAnelle",model.PostFontAnelle ?? (object)DBNull.Value)
                 ,new SqlParameter("@Sutures",model.Sutures ?? (object)DBNull.Value)
                 ,new SqlParameter("@CephalohematomaLeft", model.CephalohematomaLeft)
                 ,new SqlParameter("@CephalohematomaRight", model.CephalohematomaRight)
                 ,new SqlParameter("@HeadOther", model.HeadOther ?? (object)DBNull.Value)
                 ,new SqlParameter("@EyePupils", model.EyePupils ?? (object)DBNull.Value)
                 ,new SqlParameter("@EyeSclera", model.EyeSclera ?? (object)DBNull.Value)
                 ,new SqlParameter("@EyeConjuctiva", model.EyeConjuctiva ?? (object)DBNull.Value)
                 ,new SqlParameter("@EyeDischargeLeft", model.EyeDischargeLeft ?? (object)DBNull.Value)
                 ,new SqlParameter("@EyeDischargeRight", model.EyeDischargeRight ?? (object)DBNull.Value)
                 ,new SqlParameter("@EyeRedReflexLeft", model.EyeRedReflexLeft)
                 ,new SqlParameter("@EyeRedReflexRight", model.EyeRedReflexRight)
                 ,new SqlParameter("@EarPennaeLeft", model.EarPennaeLeft ?? (object)DBNull.Value)
                 ,new SqlParameter("@EarPennaeRight", model.EarPennaeRight ?? (object)DBNull.Value)
                 ,new SqlParameter("@EarCanalLeft", model.EarCanalLeft ?? (object)DBNull.Value)
                 ,new SqlParameter("@EarCanalRight", model.EarCanalRight ?? (object)DBNull.Value)
                 ,new SqlParameter("@EarDischarge", model.EarDischarge ?? (object)DBNull.Value)
                 ,new SqlParameter("@EarOther", model.EarOther ?? (object)DBNull.Value)
                 ,new SqlParameter("@EarPennaeNotes", model.EarPennaeNotes ?? (object)DBNull.Value)
                 ,new SqlParameter("@TMLeftNormal", model.TMLeftNormal)
                 ,new SqlParameter("@TMLeftWhite", model.TMLeftWhite)
                 ,new SqlParameter("@TMLeftRed", model.TMLeftRed)
                 ,new SqlParameter("@TMLeftRellow", model.TMLeftRellow)
                 ,new SqlParameter("@TMLeftBulging", model.TMLeftBulging)
                 ,new SqlParameter("@TMLeftMobile", model.TMLeftMobile)
                 ,new SqlParameter("@TMLeftNonMobile", model.TMLeftNonMobile)
                 ,new SqlParameter("@TMLeftRaptured", model.TMLeftRaptured)
                 ,new SqlParameter("@TMRightNormal", model.TMRightNormal)
                 ,new SqlParameter("@TMRightWhite", model.TMRightWhite)
                 ,new SqlParameter("@TMRightRed", model.TMRightRed)
                 ,new SqlParameter("@TMRightYellow", model.TMRightYellow)
                 ,new SqlParameter("@TMRightBulging", model.TMRightBulging)
                 ,new SqlParameter("@TMRightMobile", model.TMRightMobile)
                 ,new SqlParameter("@TMRightNonMobile", model.TMRightNonMobile)
                 ,new SqlParameter("@TMRightRuptured", model.TMRightRuptured)
                 ,new SqlParameter("@TMDischarge", model.TMDischarge ?? (object)DBNull.Value)
                 ,new SqlParameter("@TMOther", model.TMOther ?? (object)DBNull.Value)
                 ,new SqlParameter("@Nose", model.Nose ?? (object)DBNull.Value)
                 ,new SqlParameter("@NoseDischarge", model.NoseDischarge ?? (object)DBNull.Value)
                 ,new SqlParameter("@NoseOther", model.NoseOther ?? (object)DBNull.Value)
                 ,new SqlParameter("@Mouth", model.Mouth ?? (object)DBNull.Value)
                 ,new SqlParameter("@MouthGums", model.MouthGums ?? (object)DBNull.Value)
                 ,new SqlParameter("@MouthOther", model.MouthOther ?? (object)DBNull.Value)
                 ,new SqlParameter("@Suck", model.Suck ?? (object)DBNull.Value)
                 ,new SqlParameter("@Throat", model.Throat ?? (object)DBNull.Value)
                 ,new SqlParameter("@ThroatOther", model.ThroatOther ?? (object)DBNull.Value)
                 ,new SqlParameter("@Neck", model.Neck ?? (object)DBNull.Value)
                 ,new SqlParameter("@SwollenLymphNode", model.SwollenLymphNode ?? (object)DBNull.Value)
                 ,new SqlParameter("@NeckLeft", model.NeckLeft ?? (object)DBNull.Value)
                 ,new SqlParameter("@NeckRight", model.NeckRight ?? (object)DBNull.Value)
                 ,new SqlParameter("@NeckOther", model.NeckOther ?? (object)DBNull.Value)
                 ,new SqlParameter("@LungRespiration", model.LungRespiration ?? (object)DBNull.Value)
                 ,new SqlParameter("@LungRetratcions", model.LungRetratcions)
                 ,new SqlParameter("@LungWheezes", model.LungWheezes)
                 ,new SqlParameter("@LungBreathSound", model.LungBreathSound)
                 ,new SqlParameter("@LungDimishedLeft", model.LungDimishedLeft)
                 ,new SqlParameter("@LungDimishedRight", model.LungDimishedRight)
                 ,new SqlParameter("@LungRhonchi", model.LungRhonchi)
                 ,new SqlParameter("@LungRales", model.LungRales)
                 ,new SqlParameter("@LungIncRespRate", model.LungIncRespRate)
                 ,new SqlParameter("@LungOhter", model.LungOhter ?? (object)DBNull.Value)
                 ,new SqlParameter("@HeartRate", model.HeartRate ?? (object)DBNull.Value)
                 ,new SqlParameter("@HeartMurmur", model.HeartMurmur ?? (object)DBNull.Value)
                 ,new SqlParameter("@HeartIncreasedRate", model.HeartIncreasedRate)
                 ,new SqlParameter("@HeartDecreasedRate", model.HeartDecreasedRate)
                 ,new SqlParameter("@HeartIrregularRhythm", model.HeartIrregularRhythm)
                 ,new SqlParameter("@HeartRub", model.HeartRub)
                 ,new SqlParameter("@HeartPedal", model.HeartPedal ?? (object)DBNull.Value)
                 ,new SqlParameter("@HeartOther", model.HeartOther ?? (object)DBNull.Value)
                 ,new SqlParameter("@AbdAbdomen", model.AbdAbdomen ?? (object)DBNull.Value)
                 ,new SqlParameter("@AbdTender", model.AbdTender ?? (object)DBNull.Value)
                 ,new SqlParameter("@AbdMass", model.AbdMass ?? (object)DBNull.Value)
                 ,new SqlParameter("@AbdSize", model.AbdSize ?? (object)DBNull.Value)
                 ,new SqlParameter("@AbdMassQuality", model.AbdMassQuality ?? (object)DBNull.Value)
                 ,new SqlParameter("@AbdHernia", model.AbdHernia ?? (object)DBNull.Value)
                 ,new SqlParameter("@UmbClean", model.UmbClean ?? (object)DBNull.Value)
                 ,new SqlParameter("@UmbDischarge", model.UmbDischarge ?? (object)DBNull.Value)
                 ,new SqlParameter("@UmbErythema", model.UmbErythema )
                 ,new SqlParameter("@UmbInduration", model.UmbInduration)
                 ,new SqlParameter("@UmbWarmtoTouch", model.UmbWarmtoTouch )
                 ,new SqlParameter("@UmbHernia", model.UmbHernia ?? (object)DBNull.Value)
                 ,new SqlParameter("@UmbOther", model.UmbOther ?? (object)DBNull.Value)
                 ,new SqlParameter("@GentTesties", model.GentTesties ?? (object)DBNull.Value)
                 ,new SqlParameter("@GentHydrocele", model.GentHydrocele)
                 ,new SqlParameter("@GentUndescededLeft", model.GentUndescededLeft)
                 ,new SqlParameter("@GentUndescededRight", model.GentUndescededRight)
                 ,new SqlParameter("@GentHernia", model.GentHernia ?? (object)DBNull.Value)
                 ,new SqlParameter("@GentPenis", model.GentPenis ?? (object)DBNull.Value)
                 ,new SqlParameter("@GentMeatus", model.GentMeatus ?? (object)DBNull.Value)
                 ,new SqlParameter("@GentDischargeMale", model.GentDischargeMale ?? (object)DBNull.Value)
                 ,new SqlParameter("@GentOtherMale", model.GentOtherMale ?? (object)DBNull.Value)
                 ,new SqlParameter("@GentNormal", model.GentNormal ?? (object)DBNull.Value)
                 ,new SqlParameter("@GentLabia", model.GentLabia ?? (object)DBNull.Value)
                 ,new SqlParameter("@GentUrethra", model.GentUrethra ?? (object)DBNull.Value)
                 ,new SqlParameter("@GentDishargeFemale", model.GentDishargeFemale ?? (object)DBNull.Value)
                 ,new SqlParameter("@GentMass", model.GentMass ?? (object)DBNull.Value)
                 ,new SqlParameter("@GentSize ", model.GentSize  ?? (object)DBNull.Value)
                 ,new SqlParameter("@GentOtherFemale", model.GentOtherFemale ?? (object)DBNull.Value)
                 ,new SqlParameter("@MuscArms", model.MuscArms ?? (object)DBNull.Value)
                 ,new SqlParameter("@MuscWeekness", model.MuscWeekness ?? (object)DBNull.Value)
                 ,new SqlParameter("@MuscSwelling", model.MuscSwelling ?? (object)DBNull.Value)
                 ,new SqlParameter("@MuscTender", model.MuscTender ?? (object)DBNull.Value)
                 ,new SqlParameter("@MuscImmobile", model.MuscImmobile ?? (object)DBNull.Value)
                 ,new SqlParameter("@MuscDecStrength", model.MuscDecStrength ?? (object)DBNull.Value)
                 ,new SqlParameter("@MuscOther", model.MuscOther ?? (object)DBNull.Value)
                 ,new SqlParameter("@HandSymmetry", model.HandSymmetry ?? (object)DBNull.Value)
                 ,new SqlParameter("@HandWeekness", model.HandWeekness ?? (object)DBNull.Value)
                 ,new SqlParameter("@HandSwelling", model.HandSwelling ?? (object)DBNull.Value)
                 ,new SqlParameter("@HandTender", model.HandTender ?? (object)DBNull.Value)
                 ,new SqlParameter("@HandImmobile", model.HandImmobile ?? (object)DBNull.Value)
                 ,new SqlParameter("@HandDecStrength", model.HandDecStrength ?? (object)DBNull.Value)
                 ,new SqlParameter("@HandFingers", model.HandFingers ?? (object)DBNull.Value)
                 ,new SqlParameter("@HandBruise", model.HandBruise ?? (object)DBNull.Value)
                 ,new SqlParameter("@HandExtraDigits", model.HandExtraDigits)
                 ,new SqlParameter("@HandSyndactyly", model.HandSyndactyly)
                 ,new SqlParameter("@HandOther", model.HandOther ?? (object)DBNull.Value)
                 ,new SqlParameter("@LegSymmetry", model.LegSymmetry ?? (object)DBNull.Value)
                 ,new SqlParameter("@LegWeekness", model.LegWeekness ?? (object)DBNull.Value)
                 ,new SqlParameter("@LegFlacid", model.LegFlacid ?? (object)DBNull.Value)
                 ,new SqlParameter("@LegNomalTone", model.LegNomalTone ?? (object)DBNull.Value)
                 ,new SqlParameter("@LegSwelling", model.LegSwelling ?? (object)DBNull.Value)
                 ,new SqlParameter("@LegTender", model.LegTender ?? (object)DBNull.Value)
                 ,new SqlParameter("@LegImmobile", model.LegImmobile ?? (object)DBNull.Value)
                 ,new SqlParameter("@LegDecStrength", model.LegDecStrength ?? (object)DBNull.Value)
                 ,new SqlParameter("@LegOther", model.LegOther ?? (object)DBNull.Value)
                 ,new SqlParameter("@FeetSymmetry", model.FeetSymmetry ?? (object)DBNull.Value)
                 ,new SqlParameter("@FeetWeekness", model.FeetWeekness ?? (object)DBNull.Value)
                 ,new SqlParameter("@FeetSwelling", model.FeetSwelling ?? (object)DBNull.Value)
                 ,new SqlParameter("@FeetTender", model.FeetTender ?? (object)DBNull.Value)
                 ,new SqlParameter("@FeetImmobile", model.FeetImmobile ?? (object)DBNull.Value)
                 ,new SqlParameter("@FeetDecStrength", model.FeetDecStrength ?? (object)DBNull.Value)
                 ,new SqlParameter("@FeetClubFoot", model.FeetClubFoot ?? (object)DBNull.Value)
                 ,new SqlParameter("@FeetToes", model.FeetToes ?? (object)DBNull.Value)
                 ,new SqlParameter("@FeetExtraDigits", model.FeetExtraDigits)
                 ,new SqlParameter("@FeetSyndactyly", model.FeetSyndactyly)
                 ,new SqlParameter("@FeetOther", model.FeetOther ?? (object)DBNull.Value)
                 ,new SqlParameter("@HipSymmetry", model.HipSymmetry ?? (object)DBNull.Value)
                 ,new SqlParameter("@HipLeft", model.HipLeft ?? (object)DBNull.Value)
                 ,new SqlParameter("@HipRight", model.HipRight ?? (object)DBNull.Value)
                 ,new SqlParameter("@NeuroAwake", model.NeuroAwake)
                 ,new SqlParameter("@NeuroAlert", model.NeuroAlert)
                 ,new SqlParameter("@NeuroActive", model.NeuroActive)
                 ,new SqlParameter("@NeuroDecConsciousness", model.NeuroDecConsciousness)
                 ,new SqlParameter("@NeuroAgitated", model.NeuroAgitated)
                 ,new SqlParameter("@NeuroConvelsions", model.NeuroConvelsions)
                 ,new SqlParameter("@NeuroListLess", model.NeuroListLess)
                 ,new SqlParameter("@NeuroLethargic", model.NeuroLethargic)
                 ,new SqlParameter("@NeuroFlaccid", model.NeuroFlaccid)
                 ,new SqlParameter("@ReflexMoro", model.ReflexMoro)
                 ,new SqlParameter("@ReflexGrasp", model.ReflexGrasp)
                 ,new SqlParameter("@ReflexRooting", model.ReflexRooting)
                 ,new SqlParameter("@ReflexGalant", model.ReflexGalant)
                 ,new SqlParameter("@ReflexStepping", model.ReflexStepping)
                 ,new SqlParameter("@ReflexOther", model.ReflexOther ?? (object)DBNull.Value)
                 ,new SqlParameter("@SkinNormal", model.SkinNormal ?? (object)DBNull.Value)
                 ,new SqlParameter("@Rashflat", model.Rashflat)
                 ,new SqlParameter("@RashRaised", model.RashRaised)
                 ,new SqlParameter("@RashErythema", model.RashErythema)
                 ,new SqlParameter("@RashMacules", model.RashMacules)
                 ,new SqlParameter("@RashPapules", model.RashPapules)
                 ,new SqlParameter("@RashPetechie", model.RashPetechie)
                 ,new SqlParameter("@RashSize", model.RashSize ?? (object)DBNull.Value)
                 ,new SqlParameter("@RashOther", model.RashOther ?? (object)DBNull.Value)
                 ,new SqlParameter("@BfSuck", model.BfSuck )
                 ,new SqlParameter("@BfLatchingOn", model.BfLatchingOn)
                 ,new SqlParameter("@BfSpitting", model.BfSpitting)
                 ,new SqlParameter("@BfVomiting", model.BfVomiting)
                 ,new SqlParameter("@BfNasalObstruction", model.BfNasalObstruction)
                 ,new SqlParameter("@BfOther", model.BfOther ?? (object)DBNull.Value)
                 ,new SqlParameter("@DsFever", model.DsFever )
                 ,new SqlParameter("@DsPoorFeeding", model.DsPoorFeeding)
                 ,new SqlParameter("@DsCrying", model.DsCrying)
                 ,new SqlParameter("@DsLethargy", model.DsLethargy)
                 ,new SqlParameter("@DsHardToWakeup", model.DsHardToWakeup)
                 ,new SqlParameter("@DsNoUrination", model.DsNoUrination)
                 ,new SqlParameter("@DsNoBowelMovement", model.DsNoBowelMovement)
                 ,new SqlParameter("@DsVomiting", model.DsVomiting)
                 ,new SqlParameter("@DsDiarrhea", model.DsDiarrhea)
                 ,new SqlParameter("@DsReturn", model.DsReturn)
                 ,new SqlParameter("@Hgb", model.Hgb ?? (object)DBNull.Value)
                 ,new SqlParameter("@BloodGroup", model.BloodGroup ?? (object)DBNull.Value)
                 ,new SqlParameter("@HepB", model.HepB)
                 ,new SqlParameter("@Protein", model.Protein ?? (object)DBNull.Value)
                 ,new SqlParameter("@Glucose", model.Glucose ?? (object)DBNull.Value)
                 ,new SqlParameter("@BloodSugar", model.BloodSugar ?? (object)DBNull.Value)
                 ,new SqlParameter("@WBC", model.WBC ?? (object)DBNull.Value)
                 ,new SqlParameter("@GramStain", model.GramStain ?? (object)DBNull.Value)
                 ,new SqlParameter("@Keytone", model.Keytone ?? (object)DBNull.Value)
                 ,new SqlParameter("@Blood", model.Blood ?? (object)DBNull.Value)
                 ,new SqlParameter("@Polio", model.Polio)
                 ,new SqlParameter("@BCG ", model.BCG )
                 ,new SqlParameter("@Bilirubin", model.Bilirubin ?? (object)DBNull.Value)
                 ,new SqlParameter("@Notes", model.Notes ?? (object)DBNull.Value)
                 ,new SqlParameter("@Plan", model.Plan ?? (object)DBNull.Value)
                ,_error
                ,_message
                ,_ID
            };
            var parms = "@PatientId,@InfantDOB,@InfantAge,@Gender,@DeliveryCondition,@DeliveryTerm,@DeliveryHospital,@DeliveryMaternityHome,@DeliveryHome,@Alert,@Listless,@Jaundice,@Active,@Agitated,@Pale,@Smiling,@Convulsions,@Crying,@NonResponse,@Lethargic,@ColorPink,@Other,@InfantCondition,@BreastFeeding,@FeedingCondition,@Temperature,@Weight,@WeightPercentile,@BirthWieght,@BirthWieghtPercentile,@Length,@LengthPercentile,@HC,@HCPercentile,@Head,@AntFontAnelle,@PostFontAnelle,@Sutures,@CephalohematomaLeft,@CephalohematomaRight,@HeadOther,@EyePupils,@EyeSclera,@EyeConjuctiva,@EyeDischargeLeft,@EyeDischargeRight,@EyeRedReflexLeft,@EyeRedReflexRight,@EarPennaeLeft,@EarPennaeRight,@EarCanalLeft,@EarCanalRight,@EarDischarge,@EarPennaeNotes,@EarOther,@TMLeftNormal,@TMLeftWhite,@TMLeftRed,@TMLeftRellow,@TMLeftBulging,@TMLeftMobile,@TMLeftNonMobile,@TMLeftRaptured,@TMRightNormal,@TMRightWhite,@TMRightRed,@TMRightYellow,@TMRightBulging,@TMRightMobile,@TMRightNonMobile,@TMRightRuptured,@TMDischarge,@TMOther,@Nose,@NoseDischarge,@NoseOther,@Mouth,@MouthGums,@MouthOther,@Suck,@Throat,@ThroatOther,@Neck,@SwollenLymphNode,@NeckLeft,@NeckRight,@NeckOther,@LungRespiration,@LungRetratcions,@LungWheezes,@LungBreathSound,@LungDimishedLeft,@LungDimishedRight,@LungRhonchi,@LungRales,@LungIncRespRate,@LungOhter,@HeartRate,@HeartMurmur,@HeartIncreasedRate,@HeartDecreasedRate,@HeartIrregularRhythm,@HeartRub,@HeartPedal,@HeartOther,@AbdAbdomen,@AbdTender,@AbdMass,@AbdSize,@AbdMassQuality,@AbdHernia,@UmbClean,@UmbDischarge,@UmbErythema,@UmbInduration,@UmbWarmtoTouch,@UmbHernia,@UmbOther,@GentTesties,@GentHydrocele,@GentUndescededLeft,@GentUndescededRight,@GentHernia,@GentPenis,@GentMeatus,@GentDischargeMale,@GentOtherMale,@GentNormal,@GentLabia,@GentUrethra,@GentDishargeFemale,@GentMass,@GentSize,@GentOtherFemale,@MuscArms,@MuscWeekness,@MuscSwelling,@MuscTender,@MuscImmobile,@MuscDecStrength,@MuscOther,@HandSymmetry,@HandWeekness,@HandSwelling,@HandTender,@HandImmobile,@HandDecStrength,@HandFingers,@HandBruise,@HandExtraDigits,@HandSyndactyly,@HandOther,@LegSymmetry,@LegWeekness,@LegFlacid,@LegNomalTone,@LegSwelling,@LegTender,@LegImmobile,@LegDecStrength,@LegOther,@FeetSymmetry,@FeetWeekness,@FeetSwelling,@FeetTender,@FeetImmobile,@FeetDecStrength,@FeetClubFoot,@FeetToes,@FeetExtraDigits,@FeetSyndactyly,@FeetOther,@HipSymmetry,@HipLeft,@HipRight,@NeuroAwake,@NeuroAlert,@NeuroActive,@NeuroDecConsciousness,@NeuroAgitated,@NeuroConvelsions,@NeuroListLess,@NeuroLethargic,@NeuroFlaccid,@ReflexMoro,@ReflexGrasp,@ReflexRooting,@ReflexGalant,@ReflexStepping,@ReflexOther,@SkinNormal,@Rashflat,@RashRaised,@RashErythema,@RashMacules,@RashPapules,@RashPetechie,@RashSize,@RashOther,@BfSuck,@BfLatchingOn,@BfSpitting,@BfVomiting,@BfNasalObstruction,@BfOther,@DsFever,@DsPoorFeeding,@DsCrying,@DsLethargy,@DsHardToWakeup,@DsNoUrination,@DsNoBowelMovement,@DsVomiting,@DsDiarrhea,@DsReturn,@Hgb,@BloodGroup,@HepB,@Protein,@Glucose,@BloodSugar,@WBC,@GramStain,@Keytone,@Blood,@Polio,@BCG,@Bilirubin,@Notes,@Plan";
            var res = db.Database.ExecuteSqlCommand("sp_PostNatal_Infant_Insert "+ parms + ",@Error out,@Message out,@ID out", parameters);

            outparam.Error = (bool)_error.Value;
            outparam.Message = _message.Value.ToString();
            if (!outparam.Error)
            {
                outparam.IDInt32 = (int)_ID.Value;
                model.PostNatalInfantId = (int)_ID.Value;

            }
            return model;
        }

        public override PostNatal_Infant Update(PostNatal_Infant model, out OutParamModel outparam)
        {
            outparam = new OutParamModel();
            SqlParameter[] parameters =
            {
                  new SqlParameter("@PostNatalInfantId",model.PostNatalInfantId)
                 ,new SqlParameter("@PatientId",model.PatientId ?? (object)DBNull.Value)
                 ,new SqlParameter("@InfantDOB",model.InfantDOB ?? (object)DBNull.Value)
                 ,new SqlParameter("@InfantAge",model.InfantAge ?? (object)DBNull.Value)
                 ,new SqlParameter("@Gender",model.Gender ?? (object)DBNull.Value)
                 ,new SqlParameter("@DeliveryCondition",model.DeliveryCondition ?? (object)DBNull.Value)
                 ,new SqlParameter("@DeliveryTerm",model.DeliveryTerm ?? (object)DBNull.Value)
                 ,new SqlParameter("@DeliveryHospital",model.DeliveryHospital )
                 ,new SqlParameter("@DeliveryMaternityHome",model.DeliveryMaternityHome )
                 ,new SqlParameter("@DeliveryHome",model.DeliveryHome)
                 ,new SqlParameter("@Alert", model.Alert)
                 ,new SqlParameter("@ListLess", model.Listless)
                 ,new SqlParameter("@Jaundice", model.Jaundice)
                 ,new SqlParameter("@Active", model.Active)
                 ,new SqlParameter("@Agitated", model.Agitated)
                 ,new SqlParameter("@Pale", model.Pale)
                 ,new SqlParameter("@Smiling", model.Smiling)
                 ,new SqlParameter("@Convulsions", model.Convulsions)
                 ,new SqlParameter("@Crying", model.Crying)
                 ,new SqlParameter("@NonResponse", model.NonResponse)
                 ,new SqlParameter("@Lethargic", model.Lethargic)
                 ,new SqlParameter("@ColorPink", model.ColorPink)
                 ,new SqlParameter("@Other", model.Other)
                 ,new SqlParameter("@InfantCondition",model.InfantCondition ?? (object)DBNull.Value)
                 ,new SqlParameter("@BreastFeeding", model.BreastFeeding)
                 ,new SqlParameter("@FeedingCondition",model.FeedingCondition ?? (object)DBNull.Value)
                 ,new SqlParameter("@Temperature",model.Temperature ?? (object)DBNull.Value)
                 ,new SqlParameter("@Weight",model.Weight ?? (object)DBNull.Value)
                 ,new SqlParameter("@WeightPercentile",model.WeightPercentile ?? (object)DBNull.Value)
                 ,new SqlParameter("@BirthWieght",model.BirthWieght ?? (object)DBNull.Value)
                 ,new SqlParameter("@BirthWieghtPercentile",model.BirthWieghtPercentile ?? (object)DBNull.Value)
                 ,new SqlParameter("@Length",model.Length ?? (object)DBNull.Value)
                 ,new SqlParameter("@LengthPercentile",model.LengthPercentile ?? (object)DBNull.Value)
                 ,new SqlParameter("@HC",model.HC ?? (object)DBNull.Value)
                 ,new SqlParameter("@HCPercentile",model.HCPercentile ?? (object)DBNull.Value)
                 ,new SqlParameter("@Head",model.Head ?? (object)DBNull.Value)
                 ,new SqlParameter("@AntFontAnelle",model.AntFontAnelle ?? (object)DBNull.Value)
                 ,new SqlParameter("@PostFontAnelle",model.PostFontAnelle ?? (object)DBNull.Value)
                 ,new SqlParameter("@Sutures",model.Sutures ?? (object)DBNull.Value)
                 ,new SqlParameter("@CephalohematomaLeft", model.CephalohematomaLeft)
                 ,new SqlParameter("@CephalohematomaRight", model.CephalohematomaRight)
                 ,new SqlParameter("@HeadOther", model.HeadOther ?? (object)DBNull.Value)
                 ,new SqlParameter("@EyePupils", model.EyePupils ?? (object)DBNull.Value)
                 ,new SqlParameter("@EyeSclera", model.EyeSclera ?? (object)DBNull.Value)
                 ,new SqlParameter("@EyeConjuctiva", model.EyeConjuctiva ?? (object)DBNull.Value)
                 ,new SqlParameter("@EyeDischargeLeft", model.EyeDischargeLeft ?? (object)DBNull.Value)
                 ,new SqlParameter("@EyeDischargeRight", model.EyeDischargeRight ?? (object)DBNull.Value)
                 ,new SqlParameter("@EyeRedReflexLeft", model.EyeRedReflexLeft)
                 ,new SqlParameter("@EyeRedReflexRight", model.EyeRedReflexRight)
                 ,new SqlParameter("@EarPennaeLeft", model.EarPennaeLeft ?? (object)DBNull.Value)
                 ,new SqlParameter("@EarPennaeRight", model.EarPennaeRight ?? (object)DBNull.Value)
                 ,new SqlParameter("@EarCanalLeft", model.EarCanalLeft ?? (object)DBNull.Value)
                 ,new SqlParameter("@EarCanalRight", model.EarCanalRight ?? (object)DBNull.Value)
                 ,new SqlParameter("@EarDischarge", model.EarDischarge ?? (object)DBNull.Value)
                 ,new SqlParameter("@EarOther", model.EarOther ?? (object)DBNull.Value)
                 ,new SqlParameter("@EarPennaeNotes", model.EarPennaeNotes ?? (object)DBNull.Value)
                 ,new SqlParameter("@TMLeftNormal", model.TMLeftNormal)
                 ,new SqlParameter("@TMLeftWhite", model.TMLeftWhite)
                 ,new SqlParameter("@TMLeftRed", model.TMLeftRed)
                 ,new SqlParameter("@TMLeftRellow", model.TMLeftRellow)
                 ,new SqlParameter("@TMLeftBulging", model.TMLeftBulging)
                 ,new SqlParameter("@TMLeftMobile", model.TMLeftMobile)
                 ,new SqlParameter("@TMLeftNonMobile", model.TMLeftNonMobile)
                 ,new SqlParameter("@TMLeftRaptured", model.TMLeftRaptured)
                 ,new SqlParameter("@TMRightNormal", model.TMRightNormal)
                 ,new SqlParameter("@TMRightWhite", model.TMRightWhite)
                 ,new SqlParameter("@TMRightRed", model.TMRightRed)
                 ,new SqlParameter("@TMRightYellow", model.TMRightYellow)
                 ,new SqlParameter("@TMRightBulging", model.TMRightBulging)
                 ,new SqlParameter("@TMRightMobile", model.TMRightMobile)
                 ,new SqlParameter("@TMRightNonMobile", model.TMRightNonMobile)
                 ,new SqlParameter("@TMRightRuptured", model.TMRightRuptured)
                 ,new SqlParameter("@TMDischarge", model.TMDischarge ?? (object)DBNull.Value)
                 ,new SqlParameter("@TMOther", model.TMOther ?? (object)DBNull.Value)
                 ,new SqlParameter("@Nose", model.Nose ?? (object)DBNull.Value)
                 ,new SqlParameter("@NoseDischarge", model.NoseDischarge ?? (object)DBNull.Value)
                 ,new SqlParameter("@NoseOther", model.NoseOther ?? (object)DBNull.Value)
                 ,new SqlParameter("@Mouth", model.Mouth ?? (object)DBNull.Value)
                 ,new SqlParameter("@MouthGums", model.MouthGums ?? (object)DBNull.Value)
                 ,new SqlParameter("@MouthOther", model.MouthOther ?? (object)DBNull.Value)
                 ,new SqlParameter("@Suck", model.Suck ?? (object)DBNull.Value)
                 ,new SqlParameter("@Throat", model.Throat ?? (object)DBNull.Value)
                 ,new SqlParameter("@ThroatOther", model.ThroatOther ?? (object)DBNull.Value)
                 ,new SqlParameter("@Neck", model.Neck ?? (object)DBNull.Value)
                 ,new SqlParameter("@SwollenLymphNode", model.SwollenLymphNode ?? (object)DBNull.Value)
                 ,new SqlParameter("@NeckLeft", model.NeckLeft ?? (object)DBNull.Value)
                 ,new SqlParameter("@NeckRight", model.NeckRight ?? (object)DBNull.Value)
                 ,new SqlParameter("@NeckOther", model.NeckOther ?? (object)DBNull.Value)
                 ,new SqlParameter("@LungRespiration", model.LungRespiration ?? (object)DBNull.Value)
                 ,new SqlParameter("@LungRetratcions", model.LungRetratcions)
                 ,new SqlParameter("@LungWheezes", model.LungWheezes)
                 ,new SqlParameter("@LungBreathSound", model.LungBreathSound)
                 ,new SqlParameter("@LungDimishedLeft", model.LungDimishedLeft)
                 ,new SqlParameter("@LungDimishedRight", model.LungDimishedRight)
                 ,new SqlParameter("@LungRhonchi", model.LungRhonchi)
                 ,new SqlParameter("@LungRales", model.LungRales)
                 ,new SqlParameter("@LungIncRespRate", model.LungIncRespRate)
                 ,new SqlParameter("@LungOhter", model.LungOhter ?? (object)DBNull.Value)
                 ,new SqlParameter("@HeartRate", model.HeartRate ?? (object)DBNull.Value)
                 ,new SqlParameter("@HeartMurmur", model.HeartMurmur ?? (object)DBNull.Value)
                 ,new SqlParameter("@HeartIncreasedRate", model.HeartIncreasedRate)
                 ,new SqlParameter("@HeartDecreasedRate", model.HeartDecreasedRate)
                 ,new SqlParameter("@HeartIrregularRhythm", model.HeartIrregularRhythm)
                 ,new SqlParameter("@HeartRub", model.HeartRub)
                 ,new SqlParameter("@HeartPedal", model.HeartPedal ?? (object)DBNull.Value)
                 ,new SqlParameter("@HeartOther", model.HeartOther ?? (object)DBNull.Value)
                 ,new SqlParameter("@AbdAbdomen", model.AbdAbdomen ?? (object)DBNull.Value)
                 ,new SqlParameter("@AbdTender", model.AbdTender ?? (object)DBNull.Value)
                 ,new SqlParameter("@AbdMass", model.AbdMass ?? (object)DBNull.Value)
                 ,new SqlParameter("@AbdSize", model.AbdSize ?? (object)DBNull.Value)
                 ,new SqlParameter("@AbdMassQuality", model.AbdMassQuality ?? (object)DBNull.Value)
                 ,new SqlParameter("@AbdHernia", model.AbdHernia ?? (object)DBNull.Value)
                 ,new SqlParameter("@UmbClean", model.UmbClean ?? (object)DBNull.Value)
                 ,new SqlParameter("@UmbDischarge", model.UmbDischarge ?? (object)DBNull.Value)
                 ,new SqlParameter("@UmbErythema", model.UmbErythema )
                 ,new SqlParameter("@UmbInduration", model.UmbInduration)
                 ,new SqlParameter("@UmbWarmtoTouch", model.UmbWarmtoTouch )
                 ,new SqlParameter("@UmbHernia", model.UmbHernia ?? (object)DBNull.Value)
                 ,new SqlParameter("@UmbOther", model.UmbOther ?? (object)DBNull.Value)
                 ,new SqlParameter("@GentTesties", model.GentTesties ?? (object)DBNull.Value)
                 ,new SqlParameter("@GentHydrocele", model.GentHydrocele)
                 ,new SqlParameter("@GentUndescededLeft", model.GentUndescededLeft)
                 ,new SqlParameter("@GentUndescededRight", model.GentUndescededRight)
                 ,new SqlParameter("@GentHernia", model.GentHernia ?? (object)DBNull.Value)
                 ,new SqlParameter("@GentPenis", model.GentPenis ?? (object)DBNull.Value)
                 ,new SqlParameter("@GentMeatus", model.GentMeatus ?? (object)DBNull.Value)
                 ,new SqlParameter("@GentDischargeMale", model.GentDischargeMale ?? (object)DBNull.Value)
                 ,new SqlParameter("@GentOtherMale", model.GentOtherMale ?? (object)DBNull.Value)
                 ,new SqlParameter("@GentNormal", model.GentNormal ?? (object)DBNull.Value)
                 ,new SqlParameter("@GentLabia", model.GentLabia ?? (object)DBNull.Value)
                 ,new SqlParameter("@GentUrethra", model.GentUrethra ?? (object)DBNull.Value)
                 ,new SqlParameter("@GentDishargeFemale", model.GentDishargeFemale ?? (object)DBNull.Value)
                 ,new SqlParameter("@GentMass", model.GentMass ?? (object)DBNull.Value)
                 ,new SqlParameter("@GentSize ", model.GentSize  ?? (object)DBNull.Value)
                 ,new SqlParameter("@GentOtherFemale", model.GentOtherFemale ?? (object)DBNull.Value)
                 ,new SqlParameter("@MuscArms", model.MuscArms ?? (object)DBNull.Value)
                 ,new SqlParameter("@MuscWeekness", model.MuscWeekness ?? (object)DBNull.Value)
                 ,new SqlParameter("@MuscSwelling", model.MuscSwelling ?? (object)DBNull.Value)
                 ,new SqlParameter("@MuscTender", model.MuscTender ?? (object)DBNull.Value)
                 ,new SqlParameter("@MuscImmobile", model.MuscImmobile ?? (object)DBNull.Value)
                 ,new SqlParameter("@MuscDecStrength", model.MuscDecStrength ?? (object)DBNull.Value)
                 ,new SqlParameter("@MuscOther", model.MuscOther ?? (object)DBNull.Value)
                 ,new SqlParameter("@HandSymmetry", model.HandSymmetry ?? (object)DBNull.Value)
                 ,new SqlParameter("@HandWeekness", model.HandWeekness ?? (object)DBNull.Value)
                 ,new SqlParameter("@HandSwelling", model.HandSwelling ?? (object)DBNull.Value)
                 ,new SqlParameter("@HandTender", model.HandTender ?? (object)DBNull.Value)
                 ,new SqlParameter("@HandImmobile", model.HandImmobile ?? (object)DBNull.Value)
                 ,new SqlParameter("@HandDecStrength", model.HandDecStrength ?? (object)DBNull.Value)
                 ,new SqlParameter("@HandFingers", model.HandFingers ?? (object)DBNull.Value)
                 ,new SqlParameter("@HandBruise", model.HandBruise ?? (object)DBNull.Value)
                 ,new SqlParameter("@HandExtraDigits", model.HandExtraDigits)
                 ,new SqlParameter("@HandSyndactyly", model.HandSyndactyly)
                 ,new SqlParameter("@HandOther", model.HandOther ?? (object)DBNull.Value)
                 ,new SqlParameter("@LegSymmetry", model.LegSymmetry ?? (object)DBNull.Value)
                 ,new SqlParameter("@LegWeekness", model.LegWeekness ?? (object)DBNull.Value)
                 ,new SqlParameter("@LegFlacid", model.LegFlacid ?? (object)DBNull.Value)
                 ,new SqlParameter("@LegNomalTone", model.LegNomalTone ?? (object)DBNull.Value)
                 ,new SqlParameter("@LegSwelling", model.LegSwelling ?? (object)DBNull.Value)
                 ,new SqlParameter("@LegTender", model.LegTender ?? (object)DBNull.Value)
                 ,new SqlParameter("@LegImmobile", model.LegImmobile ?? (object)DBNull.Value)
                 ,new SqlParameter("@LegDecStrength", model.LegDecStrength ?? (object)DBNull.Value)
                 ,new SqlParameter("@LegOther", model.LegOther ?? (object)DBNull.Value)
                 ,new SqlParameter("@FeetSymmetry", model.FeetSymmetry ?? (object)DBNull.Value)
                 ,new SqlParameter("@FeetWeekness", model.FeetWeekness ?? (object)DBNull.Value)
                 ,new SqlParameter("@FeetSwelling", model.FeetSwelling ?? (object)DBNull.Value)
                 ,new SqlParameter("@FeetTender", model.FeetTender ?? (object)DBNull.Value)
                 ,new SqlParameter("@FeetImmobile", model.FeetImmobile ?? (object)DBNull.Value)
                 ,new SqlParameter("@FeetDecStrength", model.FeetDecStrength ?? (object)DBNull.Value)
                 ,new SqlParameter("@FeetClubFoot", model.FeetClubFoot ?? (object)DBNull.Value)
                 ,new SqlParameter("@FeetToes", model.FeetToes ?? (object)DBNull.Value)
                 ,new SqlParameter("@FeetExtraDigits", model.FeetExtraDigits)
                 ,new SqlParameter("@FeetSyndactyly", model.FeetSyndactyly)
                 ,new SqlParameter("@FeetOther", model.FeetOther ?? (object)DBNull.Value)
                 ,new SqlParameter("@HipSymmetry", model.HipSymmetry ?? (object)DBNull.Value)
                 ,new SqlParameter("@HipLeft", model.HipLeft ?? (object)DBNull.Value)
                 ,new SqlParameter("@HipRight", model.HipRight ?? (object)DBNull.Value)
                 ,new SqlParameter("@NeuroAwake", model.NeuroAwake)
                 ,new SqlParameter("@NeuroAlert", model.NeuroAlert)
                 ,new SqlParameter("@NeuroActive", model.NeuroActive)
                 ,new SqlParameter("@NeuroDecConsciousness", model.NeuroDecConsciousness)
                 ,new SqlParameter("@NeuroAgitated", model.NeuroAgitated)
                 ,new SqlParameter("@NeuroConvelsions", model.NeuroConvelsions)
                 ,new SqlParameter("@NeuroListLess", model.NeuroListLess)
                 ,new SqlParameter("@NeuroLethargic", model.NeuroLethargic)
                 ,new SqlParameter("@NeuroFlaccid", model.NeuroFlaccid)
                 ,new SqlParameter("@ReflexMoro", model.ReflexMoro)
                 ,new SqlParameter("@ReflexGrasp", model.ReflexGrasp)
                 ,new SqlParameter("@ReflexRooting", model.ReflexRooting)
                 ,new SqlParameter("@ReflexGalant", model.ReflexGalant)
                 ,new SqlParameter("@ReflexStepping", model.ReflexStepping)
                 ,new SqlParameter("@ReflexOther", model.ReflexOther ?? (object)DBNull.Value)
                 ,new SqlParameter("@SkinNormal", model.SkinNormal ?? (object)DBNull.Value)
                 ,new SqlParameter("@Rashflat", model.Rashflat)
                 ,new SqlParameter("@RashRaised", model.RashRaised)
                 ,new SqlParameter("@RashErythema", model.RashErythema)
                 ,new SqlParameter("@RashMacules", model.RashMacules)
                 ,new SqlParameter("@RashPapules", model.RashPapules)
                 ,new SqlParameter("@RashPetechie", model.RashPetechie)
                 ,new SqlParameter("@RashSize", model.RashSize ?? (object)DBNull.Value)
                 ,new SqlParameter("@RashOther", model.RashOther ?? (object)DBNull.Value)
                 ,new SqlParameter("@BfSuck", model.BfSuck )
                 ,new SqlParameter("@BfLatchingOn", model.BfLatchingOn)
                 ,new SqlParameter("@BfSpitting", model.BfSpitting)
                 ,new SqlParameter("@BfVomiting", model.BfVomiting)
                 ,new SqlParameter("@BfNasalObstruction", model.BfNasalObstruction)
                 ,new SqlParameter("@BfOther", model.BfOther ?? (object)DBNull.Value)
                 ,new SqlParameter("@DsFever", model.DsFever )
                 ,new SqlParameter("@DsPoorFeeding", model.DsPoorFeeding)
                 ,new SqlParameter("@DsCrying", model.DsCrying)
                 ,new SqlParameter("@DsLethargy", model.DsLethargy)
                 ,new SqlParameter("@DsHardToWakeup", model.DsHardToWakeup)
                 ,new SqlParameter("@DsNoUrination", model.DsNoUrination)
                 ,new SqlParameter("@DsNoBowelMovement", model.DsNoBowelMovement)
                 ,new SqlParameter("@DsVomiting", model.DsVomiting)
                 ,new SqlParameter("@DsDiarrhea", model.DsDiarrhea)
                 ,new SqlParameter("@DsReturn", model.DsReturn)
                 ,new SqlParameter("@Hgb", model.Hgb ?? (object)DBNull.Value)
                 ,new SqlParameter("@BloodGroup", model.BloodGroup ?? (object)DBNull.Value)
                 ,new SqlParameter("@HepB", model.HepB)
                 ,new SqlParameter("@Protein", model.Protein ?? (object)DBNull.Value)
                 ,new SqlParameter("@Glucose", model.Glucose ?? (object)DBNull.Value)
                 ,new SqlParameter("@BloodSugar", model.BloodSugar ?? (object)DBNull.Value)
                 ,new SqlParameter("@WBC", model.WBC ?? (object)DBNull.Value)
                 ,new SqlParameter("@GramStain", model.GramStain ?? (object)DBNull.Value)
                 ,new SqlParameter("@Keytone", model.Keytone ?? (object)DBNull.Value)
                 ,new SqlParameter("@Blood", model.Blood ?? (object)DBNull.Value)
                 ,new SqlParameter("@Polio", model.Polio)
                 ,new SqlParameter("@BCG ", model.BCG )
                 ,new SqlParameter("@Bilirubin", model.Bilirubin ?? (object)DBNull.Value)
                 ,new SqlParameter("@Notes", model.Notes ?? (object)DBNull.Value)
                 ,new SqlParameter("@Plan", model.Plan ?? (object)DBNull.Value)

            };
            var parms = "@PostNatalInfantId,@PatientId,@InfantDOB,@InfantAge,@Gender,@DeliveryCondition,@DeliveryTerm,@DeliveryHospital,@DeliveryMaternityHome,@DeliveryHome,@Alert,@Listless,@Jaundice,@Active,@Agitated,@Pale,@Smiling,@Convulsions,@Crying,@NonResponse,@Lethargic,@ColorPink,@Other,@InfantCondition,@BreastFeeding,@FeedingCondition,@Temperature,@Weight,@WeightPercentile,@BirthWieght,@BirthWieghtPercentile,@Length,@LengthPercentile,@HC,@HCPercentile,@Head,@AntFontAnelle,@PostFontAnelle,@Sutures,@CephalohematomaLeft,@CephalohematomaRight,@HeadOther,@EyePupils,@EyeSclera,@EyeConjuctiva,@EyeDischargeLeft,@EyeDischargeRight,@EyeRedReflexLeft,@EyeRedReflexRight,@EarPennaeLeft,@EarPennaeRight,@EarCanalLeft,@EarCanalRight,@EarDischarge,@EarPennaeNotes,@EarOther,@TMLeftNormal,@TMLeftWhite,@TMLeftRed,@TMLeftRellow,@TMLeftBulging,@TMLeftMobile,@TMLeftNonMobile,@TMLeftRaptured,@TMRightNormal,@TMRightWhite,@TMRightRed,@TMRightYellow,@TMRightBulging,@TMRightMobile,@TMRightNonMobile,@TMRightRuptured,@TMDischarge,@TMOther,@Nose,@NoseDischarge,@NoseOther,@Mouth,@MouthGums,@MouthOther,@Suck,@Throat,@ThroatOther,@Neck,@SwollenLymphNode,@NeckLeft,@NeckRight,@NeckOther,@LungRespiration,@LungRetratcions,@LungWheezes,@LungBreathSound,@LungDimishedLeft,@LungDimishedRight,@LungRhonchi,@LungRales,@LungIncRespRate,@LungOhter,@HeartRate,@HeartMurmur,@HeartIncreasedRate,@HeartDecreasedRate,@HeartIrregularRhythm,@HeartRub,@HeartPedal,@HeartOther,@AbdAbdomen,@AbdTender,@AbdMass,@AbdSize,@AbdMassQuality,@AbdHernia,@UmbClean,@UmbDischarge,@UmbErythema,@UmbInduration,@UmbWarmtoTouch,@UmbHernia,@UmbOther,@GentTesties,@GentHydrocele,@GentUndescededLeft,@GentUndescededRight,@GentHernia,@GentPenis,@GentMeatus,@GentDischargeMale,@GentOtherMale,@GentNormal,@GentLabia,@GentUrethra,@GentDishargeFemale,@GentMass,@GentSize,@GentOtherFemale,@MuscArms,@MuscWeekness,@MuscSwelling,@MuscTender,@MuscImmobile,@MuscDecStrength,@MuscOther,@HandSymmetry,@HandWeekness,@HandSwelling,@HandTender,@HandImmobile,@HandDecStrength,@HandFingers,@HandBruise,@HandExtraDigits,@HandSyndactyly,@HandOther,@LegSymmetry,@LegWeekness,@LegFlacid,@LegNomalTone,@LegSwelling,@LegTender,@LegImmobile,@LegDecStrength,@LegOther,@FeetSymmetry,@FeetWeekness,@FeetSwelling,@FeetTender,@FeetImmobile,@FeetDecStrength,@FeetClubFoot,@FeetToes,@FeetExtraDigits,@FeetSyndactyly,@FeetOther,@HipSymmetry,@HipLeft,@HipRight,@NeuroAwake,@NeuroAlert,@NeuroActive,@NeuroDecConsciousness,@NeuroAgitated,@NeuroConvelsions,@NeuroListLess,@NeuroLethargic,@NeuroFlaccid,@ReflexMoro,@ReflexGrasp,@ReflexRooting,@ReflexGalant,@ReflexStepping,@ReflexOther,@SkinNormal,@Rashflat,@RashRaised,@RashErythema,@RashMacules,@RashPapules,@RashPetechie,@RashSize,@RashOther,@BfSuck,@BfLatchingOn,@BfSpitting,@BfVomiting,@BfNasalObstruction,@BfOther,@DsFever,@DsPoorFeeding,@DsCrying,@DsLethargy,@DsHardToWakeup,@DsNoUrination,@DsNoBowelMovement,@DsVomiting,@DsDiarrhea,@DsReturn,@Hgb,@BloodGroup,@HepB,@Protein,@Glucose,@BloodSugar,@WBC,@GramStain,@Keytone,@Blood,@Polio,@BCG,@Bilirubin,@Notes,@Plan";
            var res = db.Database.ExecuteSqlCommand("sp_PostNatal_Infant_Update " + parms , parameters);
            outparam.Error = res > 0 ? false : true;
            return model;
        }

        public override List<PostNatal_Infant> SelectAll(out OutParamModel outparam)
        {
            outparam = new OutParamModel();
            var res = db.Database.SqlQuery<PostNatal_Infant>("exec sp_PostNatal_Infant_SelectAll").ToList();
            return res;
        }
        public override PostNatal_Infant SelectByID(int ID, out OutParamModel outparam)
        {
            outparam = new OutParamModel();
            var result = db.Database.SqlQuery<PostNatal_Infant>("exec sp_PostNatal_Infant_SelectByID @PostNatalInfantId", new SqlParameter("@PostNatalInfantId", ID)).ToList().FirstOrDefault();
            return result;
        }
        public override PostNatal_Infant Delete(int ID, out OutParamModel outparam)
        {
            outparam = new OutParamModel();
            var result = db.Database.ExecuteSqlCommand("sp_PostNatal_Infant_Delete @PostNatalInfantId", new SqlParameter("@PostNatalInfantId", ID));
            outparam.Error = result > 0 ? false : true;
            return new PostNatal_Infant();
        }
    }
}