using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MaternityCareSystem.Areas.PN.DataModels
{
    public class PostNatal_Infant
    {
        public int PostNatalInfantId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public string PatientName { get; set; }
        [DisplayFormat(DataFormatString = "{0: dd-MM-yyyy}")]
        public Nullable<System.DateTime> InfantDOB { get; set; }
        public string InfantAge { get; set; }
        public string Gender { get; set; }
        public string DeliveryCondition { get; set; }
        public string DeliveryTerm { get; set; }
        public bool DeliveryHospital { get; set; }
        public bool DeliveryMaternityHome { get; set; }
        public bool DeliveryHome { get; set; }
        public bool Alert { get; set; }
        public bool Listless { get; set; }
        public bool Jaundice { get; set; }
        public bool Active { get; set; }
        public bool Agitated { get; set; }
        public bool Pale { get; set; }
        public bool Smiling { get; set; }
        public bool Convulsions { get; set; }
        public bool Crying { get; set; }
        public bool NonResponse { get; set; }
        public bool Lethargic { get; set; }
        public bool ColorPink { get; set; }
        public bool Other { get; set; }
        public string InfantCondition { get; set; }
        public bool BreastFeeding { get; set; }
        public string FeedingCondition { get; set; }
        [Required(ErrorMessage ="Enter Temperature")]
        public Nullable<decimal> Temperature { get; set; }
        [Required(ErrorMessage = "Enter Weight")]
        public Nullable<decimal> Weight { get; set; }
        [Required(ErrorMessage = "Enter Percentile")]
        public string WeightPercentile { get; set; }
        [Required(ErrorMessage = "Enter Birth Wieght")]
        public Nullable<decimal> BirthWieght { get; set; }
        [Required(ErrorMessage = "Enter Percentile")]
        public string BirthWieghtPercentile { get; set; }
        [Required(ErrorMessage = "Enter Length")]
        public string Length { get; set; }
        [Required(ErrorMessage = "Enter Percentile")]
        public string LengthPercentile { get; set; }
        [Required(ErrorMessage = "Enter HC")]
        public string HC { get; set; }
        [Required(ErrorMessage = "Enter Percentile")]
        public string HCPercentile { get; set; }
        public string Head { get; set; }
        public string AntFontAnelle { get; set; }
        public string PostFontAnelle { get; set; }
        public string Sutures { get; set; }
        public bool CephalohematomaLeft { get; set; }
        public bool CephalohematomaRight { get; set; }
        public string HeadOther { get; set; }
        public string EyePupils { get; set; }
        public string EyeSclera { get; set; }
        public string EyeConjuctiva { get; set; }
        public string EyeDischargeLeft { get; set; }
        public string EyeDischargeRight { get; set; }
        public bool EyeRedReflexLeft { get; set; }
        public bool EyeRedReflexRight { get; set; }
        public string EarPennaeLeft { get; set; }
        public string EarPennaeRight { get; set; }
        public string EarCanalLeft { get; set; }
        public string EarCanalRight { get; set; }
        public string EarDischarge { get; set; }
        public string EarPennaeNotes { get; set; }
        public string EarOther { get; set; }
        public bool TMLeftNormal { get; set; }
        public bool TMLeftWhite { get; set; }
        public bool TMLeftRed { get; set; }
        public bool TMLeftRellow { get; set; }
        public bool TMLeftBulging { get; set; }
        public bool TMLeftMobile { get; set; }
        public bool TMLeftNonMobile { get; set; }
        public bool TMLeftRaptured { get; set; }
        public bool TMRightNormal { get; set; }
        public bool TMRightWhite { get; set; }
        public bool TMRightRed { get; set; }
        public bool TMRightYellow { get; set; }
        public bool TMRightBulging { get; set; }
        public bool TMRightMobile { get; set; }
        public bool TMRightNonMobile { get; set; }
        public bool TMRightRuptured { get; set; }
        public string TMDischarge { get; set; }
        public string TMOther { get; set; }
        public string Nose { get; set; }
        public string NoseDischarge { get; set; }
        public string NoseOther { get; set; }
        public string Mouth { get; set; }
        public string MouthGums { get; set; }
        public string MouthOther { get; set; }
        public string Suck { get; set; }
        public string Throat { get; set; }
        public string ThroatOther { get; set; }
        public string Neck { get; set; }
        public string SwollenLymphNode { get; set; }
        public string NeckLeft { get; set; }
        public string NeckRight { get; set; }
        public string NeckOther { get; set; }
        public string LungRespiration { get; set; }
        public bool LungRetratcions { get; set; }
        public bool LungWheezes { get; set; }
        public bool LungBreathSound { get; set; }
        public bool LungDimishedLeft { get; set; }
        public bool LungDimishedRight { get; set; }
        public bool LungRhonchi { get; set; }
        public bool LungRales { get; set; }
        public bool LungIncRespRate { get; set; }
        public string LungOhter { get; set; }
        public string HeartRate { get; set; }
        public string HeartMurmur { get; set; }
        public bool HeartIncreasedRate { get; set; }
        public bool HeartDecreasedRate { get; set; }
        public bool HeartIrregularRhythm { get; set; }
        public bool HeartRub { get; set; }
        public string HeartPedal { get; set; }
        public string HeartOther { get; set; }
        public string AbdAbdomen { get; set; }
        public string AbdTender { get; set; }
        public string AbdMass { get; set; }
        public Nullable<decimal> AbdSize { get; set; }
        public string AbdMassQuality { get; set; }
        public string AbdHernia { get; set; }
        public string UmbClean { get; set; }
        public string UmbDischarge { get; set; }
        public bool UmbErythema { get; set; }
        public bool UmbInduration { get; set; }
        public bool UmbWarmtoTouch { get; set; }
        public string UmbHernia { get; set; }
        public string UmbOther { get; set; }
        public string GentTesties { get; set; }
        public bool GentHydrocele { get; set; }
        public bool GentUndescededLeft { get; set; }
        public bool GentUndescededRight { get; set; }
        public string GentHernia { get; set; }
        public string GentPenis { get; set; }
        public string GentMeatus { get; set; }
        public string GentDischargeMale { get; set; }
        public string GentOtherMale { get; set; }
        public string GentNormal { get; set; }
        public string GentLabia { get; set; }
        public string GentUrethra { get; set; }
        public string GentDishargeFemale { get; set; }
        public string GentMass { get; set; }
        public Nullable<decimal> GentSize { get; set; }
        public string GentOtherFemale { get; set; }
        public string MuscArms { get; set; }
        public string MuscWeekness { get; set; }
        public string MuscSwelling { get; set; }
        public string MuscTender { get; set; }
        public string MuscImmobile { get; set; }
        public string MuscDecStrength { get; set; }
        public string MuscOther { get; set; }
        public string HandSymmetry { get; set; }
        public string HandWeekness { get; set; }
        public string HandSwelling { get; set; }
        public string HandTender { get; set; }
        public string HandImmobile { get; set; }
        public string HandDecStrength { get; set; }
        public string HandFingers { get; set; }
        public string HandBruise { get; set; }
        public bool HandExtraDigits { get; set; }
        public bool HandSyndactyly { get; set; }
        public string HandOther { get; set; }
        public string LegSymmetry { get; set; }
        public string LegWeekness { get; set; }
        public string LegFlacid { get; set; }
        public string LegNomalTone { get; set; }
        public string LegSwelling { get; set; }
        public string LegTender { get; set; }
        public string LegImmobile { get; set; }
        public string LegDecStrength { get; set; }
        public string LegOther { get; set; }
        public string FeetSymmetry { get; set; }
        public string FeetWeekness { get; set; }
        public string FeetSwelling { get; set; }
        public string FeetTender { get; set; }
        public string FeetImmobile { get; set; }
        public string FeetDecStrength { get; set; }
        public string FeetClubFoot { get; set; }
        public string FeetToes { get; set; }
        public bool FeetExtraDigits { get; set; }
        public bool FeetSyndactyly { get; set; }
        public string FeetOther { get; set; }
        public string HipSymmetry { get; set; }
        public string HipLeft { get; set; }
        public string HipRight { get; set; }
        public bool NeuroAwake { get; set; }
        public bool NeuroAlert { get; set; }
        public bool NeuroActive { get; set; }
        public bool NeuroDecConsciousness { get; set; }
        public bool NeuroAgitated { get; set; }
        public bool NeuroConvelsions { get; set; }
        public bool NeuroListLess { get; set; }
        public bool NeuroLethargic { get; set; }
        public bool NeuroFlaccid { get; set; }
        public bool ReflexMoro { get; set; }
        public bool ReflexGrasp { get; set; }
        public bool ReflexRooting { get; set; }
        public bool ReflexGalant { get; set; }
        public bool ReflexStepping { get; set; }
        public string ReflexOther { get; set; }
        public string SkinNormal { get; set; }
        public bool Rashflat { get; set; }
        public bool RashRaised { get; set; }
        public bool RashErythema { get; set; }
        public bool RashMacules { get; set; }
        public bool RashPapules { get; set; }
        public bool RashPetechie { get; set; }
        public Nullable<decimal> RashSize { get; set; }
        public string RashOther { get; set; }
        public bool BfSuck { get; set; }
        public bool BfLatchingOn { get; set; }
        public bool BfSpitting { get; set; }
        public bool BfVomiting { get; set; }
        public bool BfNasalObstruction { get; set; }
        public string BfOther { get; set; }
        public bool DsFever { get; set; }
        public bool DsPoorFeeding { get; set; }
        public bool DsCrying { get; set; }
        public bool DsLethargy { get; set; }
        public bool DsHardToWakeup { get; set; }
        public bool DsNoUrination { get; set; }
        public bool DsNoBowelMovement { get; set; }
        public bool DsVomiting { get; set; }
        public bool DsDiarrhea { get; set; }
        public bool DsReturn { get; set; }
        public string Hgb { get; set; }
        public string BloodGroup { get; set; }
        public bool HepB { get; set; }
        public string Protein { get; set; }
        public string Glucose { get; set; }
        public string BloodSugar { get; set; }
        public string WBC { get; set; }
        public string GramStain { get; set; }
        public string Keytone { get; set; }
        public string Blood { get; set; }
        public bool Polio { get; set; }
        public bool BCG { get; set; }
        public string Bilirubin { get; set; }
        public string Notes { get; set; }
        public string Plan { get; set; }
    }
}